SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
DROP TABLE IF EXISTS `agenda_escala`;
CREATE TABLE `agenda_escala`  (
  `cd_escala_agenda` int NOT NULL AUTO_INCREMENT,
  `cd_agenda` int NULL DEFAULT NULL,
  `cd_dia` enum('segunda','terca','quarta','quinta','sexta','sabado','domingo') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `nr_dia` int NOT NULL,
  `qtde_proc` int NULL DEFAULT NULL,
  `dt_inicial` date NULL DEFAULT NULL,
  `dt_fim` date NULL DEFAULT NULL,
  `hr_inicial` time NOT NULL,
  `hr_final` time NOT NULL,
  `intervalo` int NOT NULL,
  `nm_intervalo` time NULL DEFAULT NULL,
  `tp_agenda` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `situacao` enum('Cancelado','Gerado','Aberto') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `qtde_sessao` int NULL DEFAULT NULL,
  `sn_sessao` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `qtde_encaixe` int NULL DEFAULT NULL,
  `sn_particular` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `sn_convenio` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `escala_gerada` tinyint NULL DEFAULT NULL,
  `escala_manual` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `escala_diaria` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `sn_sus` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `dt_geracao` datetime NULL DEFAULT NULL,
  `usuario_geracao` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `sn_ativo` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `cd_usuario` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `usuario_up` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`cd_escala_agenda`) USING BTREE,
  INDEX `cd_agenda`(`cd_agenda` ASC) USING BTREE,
  INDEX `tp_agenda`(`tp_agenda` ASC) USING BTREE,
  CONSTRAINT `agenda_escala_ibfk_1` FOREIGN KEY (`cd_agenda`) REFERENCES `agenda` (`cd_agenda`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `agenda_escala_ibfk_2` FOREIGN KEY (`tp_agenda`) REFERENCES `tipo_atendimento` (`cd_tipo_atendimento`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 858 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;
